//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace szkolkarz
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_SOWN_LOG
    {
        public int ID { get; set; }
        public int TAPE_ID { get; set; }
        public int ADM_CERTIFICATE_ARTICLE_REF_ID { get; set; }
    
        public virtual ADM_CERTIFICATE_ARTICLE_REF ADM_CERTIFICATE_ARTICLE_REF { get; set; }
    }
}
