//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace szkolkarz
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_PLANTS
    {
        public ADM_PLANTS()
        {
            this.ADM_SOWN_LOG = new HashSet<ADM_SOWN_LOG>();
        }
    
        public int ID { get; set; }
        public string PLANT { get; set; }
        public string PRODUCTION_NO { get; set; }
    
        public virtual ICollection<ADM_SOWN_LOG> ADM_SOWN_LOG { get; set; }
    }
}
