//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace szkolkarz
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_CERTIFICATE_ARTICLE_REF
    {
        public ADM_CERTIFICATE_ARTICLE_REF()
        {
            this.ADM_SOWN_LOG = new HashSet<ADM_SOWN_LOG>();
        }
    
        public int ID { get; set; }
        public int ADM_CERTIFICATE_ID { get; set; }
        public int ADM_ARTICLE_ID { get; set; }
    
        public virtual ADM_ARTICLE ADM_ARTICLE { get; set; }
        public virtual ADM_CERTIFICATE ADM_CERTIFICATE { get; set; }
        public virtual ICollection<ADM_SOWN_LOG> ADM_SOWN_LOG { get; set; }
    }
}
