//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace szkolkarz
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_AUDIT_LOG
    {
        public int ID { get; set; }
        public string USER { get; set; }
        public string ACTION { get; set; }
        public string MESSAGE { get; set; }
        public byte[] TIME_STAMP { get; set; }
    }
}
