//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace szkolkarz
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class szkolkarzEntities : DbContext
    {
        public szkolkarzEntities()
            : base("name=szkolkarzEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADM_PLANTS> ADM_PLANTS { get; set; }
        public DbSet<ADM_SOWN_LOG> ADM_SOWN_LOG { get; set; }
        public DbSet<SEC_AUDIT_LOG> SEC_AUDIT_LOG { get; set; }
        public DbSet<SEC_ERROR_LOG> SEC_ERROR_LOG { get; set; }
        public DbSet<V_FULL_SOWN_LOG> V_FULL_SOWN_LOG { get; set; }
    }
}
