//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace szkolkarz
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_FULL_SOWN_LOG
    {
        public int TAPE_ID { get; set; }
        public System.DateTime YEAR { get; set; }
        public string key { get; set; }
        public string PRODUCTION_NO { get; set; }
    }
}
