<?xml version="1.0" encoding="utf-8"?><Database Name="szkolkarz" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CHRUPEK-PC\CHRUPEK_SERVER;Initial Catalog=szkolkarz;Integrated Security=True" SettingsObjectName="szkolkarz.Properties.Settings" SettingsPropertyName="szkolkarzConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AUDIT_LOG" Member="AUDIT_LOGs">
    <Type Name="AUDIT_LOG">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[USER]" Member="USER" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ACTION" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="MESSAGE" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="TIME_STAMP" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
    </Type>
  </Table>
  <Table Name="dbo.ADM_SOWN_LOG" Member="ADM_SOWN_LOGs">
    <Type Name="ADM_SOWN_LOG">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TAPE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="YEAR" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="PLANT" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ERROR_LOG" Member="ERROR_LOGs">
    <Type Name="ERROR_LOG">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[USER]" Member="USER" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MESSAGE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TIME_STAMP" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
    </Type>
  </Table>
</Database>