USE [szkolkarz]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ADM_TEXT_RESOURCE](
	[ID] [smallint] NOT NULL,
	[KEY] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_ADM_TEXT_RESOURCE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[ADM_PLANTS](
	[ID] [int] NOT NULL,
	[ADM_TEXT_RESOURCE_ID] [smallint] NOT NULL,
	[PRODUCTION_NO] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_ADM_PLANTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[ADM_SOWN_LOG](
	[ID] [int] NOT NULL,
	[TAPE_ID] [int] NOT NULL,
	[YEAR] [smalldatetime] NOT NULL,
	[ADM_PLANT_ID] [int] NOT NULL,
 CONSTRAINT [PK_ADM_SOWN_LOG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ADM_SOWN_LOG]  WITH CHECK ADD  CONSTRAINT [FK_ADM_SOWN_LOG_ADM_PLANT_ID] FOREIGN KEY([ADM_PLANT_ID])
REFERENCES [dbo].[ADM_PLANTS] ([ID])
GO

ALTER TABLE [dbo].[ADM_SOWN_LOG] CHECK CONSTRAINT [FK_ADM_SOWN_LOG_ADM_PLANT_ID]
GO

CREATE TABLE [dbo].[SEC_AUDIT_LOG](
	[ID] [int] NOT NULL,
	[USER] [nvarchar](100) NOT NULL,
	[ACTION] [nvarchar](50) NOT NULL,
	[MESSAGE] [nvarchar](max) NOT NULL,
	[TIME_STAMP] [timestamp] NOT NULL,
 CONSTRAINT [PK_AUDIT_LOG_1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[SEC_ERROR_LOG](
	[ID] [int] NOT NULL,
	[USER] [nvarchar](100) NOT NULL,
	[MESSAGE] [nvarchar](max) NOT NULL,
	[TIME_STAMP] [timestamp] NOT NULL,
 CONSTRAINT [PK_SEC_ERROR_LOG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[TIME_STAMP] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


