USE [szkolkarz]
GO

/****** Object:  View [dbo].[V_FULL_SOWN_LOG]    Script Date: 2014-12-06 18:23:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[V_FULL_SOWN_LOG]
AS
SELECT	ASL.ID, ASL.TAPE_ID, ASL.YEAR, AA.ARTICLE, AC.CERTIFICATE
FROM		dbo.ADM_SOWN_LOG ASL 
			INNER JOIN dbo.ADM_CERTIFICATE_ARTICLE_REF ACAR ON (ACAR.ID = ASL.ADM_CERTIFICATE_ARTICLE_REF_ID)
			INNER JOIN dbo.ADM_ARTICLE AA ON (AA.ID = ACAR.ADM_ARTICLE_ID)
			INNER JOIN dbo.ADM_CERTIFICATE AC ON (AC.ID = ACAR.ADM_CERTIFICATE_ID)
			ORDER BY ASL.YEAR DESC, AA.ARTICLE ASC;