USE [szkolkarz]
GO

/****** Object:  View [dbo].[V_FULL_SOWN_LOG]    Script Date: 2014-11-20 16:05:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [DBO].[V_FULL_SOWN_LOG] AS
SELECT
	ASL.TAPE_ID,
	ASL.YEAR,
	ATR.[KEY],
	AP.PRODUCTION_NO
		FROM ADM_SOWN_LOG ASL
		INNER JOIN ADM_PLANTS AP ON AP.ID = ASL.ADM_PLANT_ID
		INNER JOIN ADM_TEXT_RESOURCE ATR ON ATR.ID = AP.ADM_TEXT_RESOURCE_ID;
GO

